services:
  caddy:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - '3000:80'
    depends_on:
      - auth
    networks:
      - app_network

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
    deploy:
      mode: replicated
      replicas: 2
    restart: always
    ports:
      - '3001'
    volumes:
      - type: bind
        source: ./apps/auth
        target: /app
    networks:
      - app_network
    command: bun run dev --filter=auth

networks:
  app_network:
    driver: bridge
